### ISSUE TITLE
Initial theme refresh development

### ISSUE THREAD

**Issue by mikethicke** [MESH-Research/boss-child#124]
Create an instance and generate theme variations for testing and feedback for theme refresh.

[Redesign slides and surveys on Google Drive](https://drive.google.com/drive/u/0/folders/1_AbipF1vlV8BFEjRSaj0EdKbbf9nqh5a?ths=true)

## Initial setup

- [x] Create dev-2 instance for refresh
- [ ] Create duplicate base Humanities Commons sites

## Basic changes

- [ ] Alter top menu bar to allow for redesigned graphics
- [ ] Remove hamburger button from top menu
- [ ] Remove "What would you like to do?" menu
- [ ] Remove right-hand sidebar

## Theme Variations

- [ ] "Stopgap" design from Stephanie's PPTx
- [ ] Version with no side menu
- [ ] Version with grid rather than carousel
- [ ] Version with some (dummy) personalized content
