### ISSUE TITLE
Develop no-sidebar carousel theme refresh

### ISSUE THREAD

**Issue by mikethicke** [MESH-Research/boss-child#138]
Develop no-sidebar, carousel version of theme refresh.

HASTAC has requested this version be production-ready by mid-month.

[Redesign slides and surveys on Google Drive](https://drive.google.com/drive/u/0/folders/1_AbipF1vlV8BFEjRSaj0EdKbbf9nqh5a?ths=true)

Initial homepage redesign:

<img width="1317" alt="Screen Shot 2022-07-05 at 2 40 37 PM" src="https://user-images.githubusercontent.com/26980498/177402505-a8cdc33b-03e6-4b0e-8153-e87e5525cc9c.png">

Pull Request: https://github.com/MESH-Research/boss-child/pull/137

Development:

- [x] Switch font(s) to Atkinson Hyperlegible ( https://github.com/MESH-Research/boss-child/issues/139 )
- [x] Have search box collapsed by default and expand on focus ( https://github.com/MESH-Research/boss-child/issues/140 )
- [x] Redesign / rearrange top menu bar ( https://github.com/MESH-Research/boss-child/issues/141 )
- [x] Verify / fix sub-pages: ( https://github.com/MESH-Research/boss-child/issues/142 )
    - Members
    - Groups
    - Sites
    - CORE
    - Profile / settings

Content:

- [ ] Develop plans for carousel content on theme refresh ( https://github.com/mesh-research/commons/issues/383 )
- [ ] Design content area for Humanities Commons landing page ( https://github.com/MESH-Research/boss-child/issues/147 )

Testing:

- [x] Initial testing on hcommons-3.dev ( https://github.com/MESH-Research/boss-child/issues/144 )
- [ ] Final testing on hcommons-dev.org ( https://github.com/MESH-Research/boss-child/issues/145 )
- [ ] Mobile view ( https://github.com/MESH-Research/boss-child/issues/143 )

Deployment:

- [ ] Create legacy brach for organizations that don't opt-in to new design
- [ ] Merge refresh branch to main
- [ ] Deploy to production

Communication:

- [ ] Notify organizations of upcoming change, policy on opting-in. ( https://github.com/MESH-Research/boss-child/issues/146 )
- [ ] Inform users about change, especially in how navigation is changing.
    - Email / newsletter
    - Blog Post

**Comment by kfitz** [comment]
- [ ] Design content for CORE landing page ( https://github.com/MESH-Research/boss-child/issues/148 )

**Comment by bjr70** [comment]
Going in new direction as part of Next-Gen Commons project. Closing.
